apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ccjep7wuz-nodejs
  janus-idp.io/tekton: ccjep7wuz-nodejs
  backstage.io/kubernetes-id: ccjep7wuz-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ccjep7wuz-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
